apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 2  # 2 экземпляра (реплики) приложения
  selector:
    matchLabels:
      app: my-python-app  # Идентификатор для приложения
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-app
        image: my-python-app:latest  # Используем ранее собранный Docker-образ
        ports:
        - containerPort: 80